name: game_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Stephen <stephenmpoole@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.4.2
  shelf: ^0.7.2
  shelf_web_socket:
  web_socket_channel:

dev_dependencies:
  pedantic: ^1.0.0
  test:
