name: chess
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: stephenpoole <stephenmpoole@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  core_game:
   path: ../../packages/core_game

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
